baseURL = "https://2018.kloosterboerderijfestival.nl/"
languageCode = "en-us"
title = "KloosterBoerderijFestival 2018"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2

[params]
piwik     = true                         # If true, Piwik integration is enabled
piwik_url = "//analytics.biomatt.nl/"    # URL to your Piwik installation. Must End with a slash
piwik_id  = 5                             # Id of your site in Piwik
