baseURL = "https://2018.kloosterboerderijfestival.nl/"
languageCode = "en-us"
title = "KloosterBoerderijFestival 2018"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2
