backend:
  name: git-gateway
  identity_url: "https://kbf2018.netlify.com/.netlify/identity"
  gateway_url: "https://kbf2018.netlify.com/.netlify/git/github"
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  branch: master

publish_mode: editorial_workflow

media_folder: media_folder

collections: # A list of collections the CMS should be able to edit
  - name: blog # Used in routes, ie.: /admin/collections/:slug/edit
    label: Blog Post # Used in the UI, ie.: New Post
    folder: content/blog # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: Date/Time, name: date, widget: datetime}
      - {label: Post Title, name: title, widget: string}
      - {label: Content, name: body, widget: markdown}
      - {label: Author, name: author, widget: relation, collection: authors, searchFields: ["first_name", "last_name"], valueField: "title"}

  - name: settings # Used in routes, ie.: /admin/collections/:slug/edit
    label: Settings
    editor:
      preview: false
    files:
      - file: config.toml
        label: Site Settings
        name: site
        fields:
          - {label: Site Title, name: title, widget: string}
